version: '2'
services:
    test2-app:
        image: test2
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://test2-mysql:3306/test2?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    test2-mysql:
        extends:
            file: mysql.yml
            service: test2-mysql
